// Generated by https://quicktype.io

export interface VideogamesState{
  videogames: VideogamesContent[];
}

export interface VideogamesContent {
  _id:              string;
  name:             string;
  description:      string;
  released:         string;
  rating:           number;
  platforms:        Platform[];
  background_image: string;
  createdInDb:      boolean;
  genres:           Genre[];
  deleted:          boolean;
  createdAt:        string;
  updatedAt:        string;
}

export interface Genre {
  _id:       ID;
  name:      Name;
  deleted:   boolean;
  createdAt: string;
  updatedAt: string;
}

export enum ID {
  The648268F3F4950430A79E32E2 = "648268f3f4950430a79e32e2",
  The648268F3F4950430A79E32E3 = "648268f3f4950430a79e32e3",
  The648268F3F4950430A79E32E4 = "648268f3f4950430a79e32e4",
  The648268F3F4950430A79E32E5 = "648268f3f4950430a79e32e5",
  The648268F3F4950430A79E32E6 = "648268f3f4950430a79e32e6",
  The648268F3F4950430A79E32E7 = "648268f3f4950430a79e32e7",
  The648268F3F4950430A79E32E8 = "648268f3f4950430a79e32e8",
  The648268F3F4950430A79E32E9 = "648268f3f4950430a79e32e9",
  The648268F3F4950430A79E32Ea = "648268f3f4950430a79e32ea",
  The648268F3F4950430A79E32Eb = "648268f3f4950430a79e32eb",
  The648268F3F4950430A79E32Ec = "648268f3f4950430a79e32ec",
  The648268F3F4950430A79E32Ed = "648268f3f4950430a79e32ed",
  The648268F3F4950430A79E32Ee = "648268f3f4950430a79e32ee",
  The648268F3F4950430A79E32Ef = "648268f3f4950430a79e32ef",
  The648268F3F4950430A79E32F0 = "648268f3f4950430a79e32f0",
}

export enum Name {
  Action = "Action",
  Adventure = "Adventure",
  Arcade = "Arcade",
  Casual = "Casual",
  Fighting = "Fighting",
  Indie = "Indie",
  MassivelyMultiplayer = "Massively Multiplayer",
  Platformer = "Platformer",
  Puzzle = "Puzzle",
  RPG = "RPG",
  Racing = "Racing",
  Shooter = "Shooter",
  Simulation = "Simulation",
  Sports = "Sports",
  Strategy = "Strategy",
}

export enum Platform {
  Android = "Android",
  Dreamcast = "Dreamcast",
  Funciona = "funciona",
  IOS = "iOS",
  Linux = "Linux",
  MACOS = "macOS",
  MuyBien = "muy bien",
  Nintendo3DS = "Nintendo 3DS",
  NintendoSwitch = "Nintendo Switch",
  PC = "PC",
  PSVita = "PS Vita",
  PlayStation2 = "PlayStation 2",
  PlayStation3 = "PlayStation 3",
  PlayStation4 = "PlayStation 4",
  PlayStation5 = "PlayStation 5",
  Web = "Web",
  WiiU = "Wii U",
  Xbox = "Xbox",
  Xbox360 = "Xbox 360",
  XboxOne = "Xbox One",
  XboxSeriesSX = "Xbox Series S/X",
}


// // Generated by https://quicktype.io

// export interface VideogamesState {
//   [x: string]: any;
//   count:                number;
//   next:                 string;
//   previous:             null;
//   results:              Result[];
//   seo_title:            string;
//   seo_description:      string;
//   seo_keywords:         string;
//   seo_h1:               string;
//   noindex:              boolean;
//   nofollow:             boolean;
//   description:          string;
//   filters:              Filters;
//   nofollow_collections: string[];
// }

// export interface Filters {
//   years: FiltersYear[];
// }

// export interface FiltersYear {
//   from:     number;
//   to:       number;
//   filter:   string;
//   decade:   number;
//   years:    YearYear[];
//   nofollow: boolean;
//   count:    number;
// }

// export interface YearYear {
//   year:     number;
//   count:    number;
//   nofollow: boolean;
// }

// export interface Result {
//   id:                 number;
//   slug:               string;
//   name:               string;
//   released:           string;
//   tba:                boolean;
//   background_image:   string;
//   rating:             number;
//   rating_top:         number;
//   ratings:            Rating[];
//   ratings_count:      number;
//   reviews_text_count: number;
//   added:              number;
//   added_by_status:    AddedByStatus;
//   metacritic:         number;
//   playtime:           number;
//   suggestions_count:  number;
//   updated:            string;
//   user_game:          null;
//   reviews_count:      number;
//   saturated_color:    Color;
//   dominant_color:     Color;
//   platforms:          PlatformElement[];
//   parent_platforms:   ParentPlatform[];
//   genres:             Genre[];
//   stores:             Store[];
//   clip:               null;
//   tags:               Genre[];
//   esrb_rating:        EsrbRating;
//   short_screenshots:  ShortScreenshot[];
// }

// export interface AddedByStatus {
//   yet:     number;
//   owned:   number;
//   beaten:  number;
//   toplay:  number;
//   dropped: number;
//   playing: number;
// }

// export enum Color {
//   The0F0F0F = "0f0f0f",
// }

// export interface EsrbRating {
//   id:   number;
//   name: string;
//   slug: string;
// }

// export interface Genre {
//   id:               number;
//   name:             string;
//   slug:             string;
//   games_count:      number;
//   image_background: string;
//   domain?:          Domain;
//   language?:        Language;
// }

// export enum Domain {
//   AppsAppleCOM = "apps.apple.com",
//   EpicgamesCOM = "epicgames.com",
//   GogCOM = "gog.com",
//   MarketplaceXboxCOM = "marketplace.xbox.com",
//   MicrosoftCOM = "microsoft.com",
//   NintendoCOM = "nintendo.com",
//   PlayGoogleCOM = "play.google.com",
//   StorePlaystationCOM = "store.playstation.com",
//   StoreSteampoweredCOM = "store.steampowered.com",
// }

// export enum Language {
//   Eng = "eng",
// }

// export interface ParentPlatform {
//   platform: EsrbRating;
// }

// export interface PlatformElement {
//   platform:        PlatformPlatform;
//   released_at:     null | string;
//   requirements_en: Requirements | null;
//   requirements_ru: Requirements | null;
// }

// export interface PlatformPlatform {
//   id:               number;
//   name:             string;
//   slug:             string;
//   image:            null;
//   year_end:         null;
//   year_start:       number | null;
//   games_count:      number;
//   image_background: string;
// }

// export interface Requirements {
//   minimum:      string;
//   recommended?: string;
// }

// export interface Rating {
//   id:      number;
//   title:   Title;
//   count:   number;
//   percent: number;
// }

// export enum Title {
//   Exceptional = "exceptional",
//   Meh = "meh",
//   Recommended = "recommended",
//   Skip = "skip",
// }

// export interface ShortScreenshot {
//   id:    number;
//   image: string;
// }

// export interface Store {
//   id:    number;
//   store: Genre;
// }
